##Creating an array thaat starts from int 1 to 20, incremented by 3

In [33]:
import numpy as np
ar = np.array([i for i in range(1,21,3)])
print(ar)

[ 1  4  7 10 13 16 19]


##Creating an array of shape 3 with random numbers between 0 and 1

In [34]:
random_array = np.random.random(3)
print(random_array) 
print("shape of the array:", random_array.shape)

[0.07335426 0.46603407 0.08111608]
shape of the array: (3,)


Create and slice 2d array

In [35]:
array1 = np.array([[10,20,45], [30,12,16], [42,17,56]])
print("array1:\n", array1)
print("shape of array1:", array1.shape)
slice_1 =array1[0:2]
print("slice_1:\n", slice_1)
silce_2 = array1[-2:]
print("slice_2:\n", silce_2)

array1:
 [[10 20 45]
 [30 12 16]
 [42 17 56]]
shape of array1: (3, 3)
slice_1:
 [[10 20 45]
 [30 12 16]]
slice_2:
 [[30 12 16]
 [42 17 56]]


##Stacking and Splitting

In [36]:
arr = np.array([[1,3],[6,7]])
print("arr:\n", arr)
arr1 = np.array([[1,2],[3,4]])
print("arr1:\n", arr1)
vertical_stack = np.vstack((arr, arr1))
print("vertical_stack:\n", vertical_stack)
horizontal_stack = np.hstack((arr, arr1))
print("horizontal_stack:\n", horizontal_stack)
split_arr = np.hsplit(horizontal_stack, 2)
print("split_arr:\n", split_arr)
split_arr1 = np.vsplit(vertical_stack, 2)
print("split_arr1:\n", split_arr1)

arr:
 [[1 3]
 [6 7]]
arr1:
 [[1 2]
 [3 4]]
vertical_stack:
 [[1 3]
 [6 7]
 [1 2]
 [3 4]]
horizontal_stack:
 [[1 3 1 2]
 [6 7 3 4]]
split_arr:
 [array([[1, 3],
       [6, 7]]), array([[1, 2],
       [3, 4]])]
split_arr1:
 [array([[1, 3],
       [6, 7]]), array([[1, 2],
       [3, 4]])]


##Matrix Multiplication

In [37]:
x = np.array([[5,7,2],[4,5,6],[7,4,2]])
y = np.array([[4,2],[4,2],[4,2]])
print("shape of x:", x.shape)
print("shape of y:", y.shape)
result = np.matmul(x,y)
print("result:\n", result)
# x_1 = np.array([[5,7,3],[4,5,4]])
# y_1 = np.array([[4,2],[4,2]])
# mul=np.matmul(x_1,y_1)
# print("mul:\n", mul)
# Here it won't work because the number of columns in x_1 (3) does not match the number of rows in y_1 (2). For matrix multiplication to be valid, the inner dimensions must match.

shape of x: (3, 3)
shape of y: (3, 2)
result:
 [[56 28]
 [60 30]
 [52 26]]


##Shape Dimension and reshaping

In [38]:
x = np.array([2,-1,-8]) 
y= np.array ([3,1,-2]) 
print(x.shape)
print(x.ndim)
reshape_x = x.reshape(3,1)
reshape_y = y.reshape(3,1)
print("reshape_x:\n", reshape_x)
print("reshape_y:\n", reshape_y)    
print("shape of reshape_x:", reshape_x.shape)
print("shape of reshape_y:", reshape_y.ndim)

(3,)
1
reshape_x:
 [[ 2]
 [-1]
 [-8]]
reshape_y:
 [[ 3]
 [ 1]
 [-2]]
shape of reshape_x: (3, 1)
shape of reshape_y: 2


## Broadcasting

In [39]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

values = np.array([1, 2, 3])

subtraction = matrix - values
multiplication = matrix * values

print("Original matrix:")
print(matrix)

print("\nSubtraction using broadcasting:")
print(subtraction)

print("\nMultiplication using broadcasting:")
print(multiplication)


Original matrix:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Subtraction using broadcasting:
[[ 9 18 27]
 [39 48 57]
 [69 78 87]]

Multiplication using broadcasting:
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


## Systems of Linear Equations

In [40]:
A1 = np.array([
    [2, 3, -4],
    [1, -4, 0]
], dtype=float)

b1 = np.array([6, 8], dtype=float)

rank_A1 = np.linalg.matrix_rank(A1)
rank_aug1 = np.linalg.matrix_rank(np.column_stack((A1, b1)))
variables1 = A1.shape[1]

print("Rank of A:", rank_A1)
print("Rank of augmented matrix:", rank_aug1)
print("Number of variables:", variables1)

if rank_A1 != rank_aug1:
    print("No solution")
elif rank_A1 == variables1:
    print("One unique solution")
else:
    print("Infinitely many solutions")

solution1 = np.linalg.lstsq(A1, b1, rcond=None)[0]
print("One solution returned by NumPy:", solution1)
print("Because there are 3 unknowns but only 2 independent equations, the system has infinitely many solutions.")


Rank of A: 2
Rank of augmented matrix: 2
Number of variables: 3
Infinitely many solutions
One solution returned by NumPy: [ 1.6692112 -1.5826972 -1.8524173]
Because there are 3 unknowns but only 2 independent equations, the system has infinitely many solutions.


### System 2


In [41]:
A2 = np.array([
    [3, -4, 5],
    [-1, 2, -4]
], dtype=float)

b2 = np.array([10, 8], dtype=float)

rank_A2 = np.linalg.matrix_rank(A2)
rank_aug2 = np.linalg.matrix_rank(np.column_stack((A2, b2)))
variables2 = A2.shape[1]

print("Rank of A:", rank_A2)
print("Rank of augmented matrix:", rank_aug2)
print("Number of variables:", variables2)

if rank_A2 != rank_aug2:
    print("No solution")
elif rank_A2 == variables2:
    print("One unique solution")
else:
    print("Infinitely many solutions")

solution2 = np.linalg.lstsq(A2, b2, rcond=None)[0]
print("One solution returned by NumPy:", solution2)
print("Because there are 3 unknowns but only 2 independent equations, the system has infinitely many solutions.")


Rank of A: 2
Rank of augmented matrix: 2
Number of variables: 3
Infinitely many solutions
One solution returned by NumPy: [ 7.46067416 -4.62921348 -6.17977528]
Because there are 3 unknowns but only 2 independent equations, the system has infinitely many solutions.
